### ISSUE TITLE
Build a list of properties without a rule

### ISSUE THREAD

**Issue by andrewthad** [sebastiaanvisser/clay#106]
I only recently discovered clay, and it is pretty awesome. It's basically what I always wanted Lucius (from Yesod's shakespeare templates) to be. So, with the flattery out of the way, I wanted to mention something that seems to be missing. There are a few occassions where it would be useful to build inline styles like this:

```
<div style="left: 22px; top: 444px">
```

So, just the value of the style attribute. This part:

```
left: 22px; top: 444px
```

is what I'm interested in. The closest I can get is doing something like this:

```
let myCss = background blue >> fontSize (px 22)
```

and when I call `renderWith compact [] myCss` on that, I get this:

```
{background:rgb(0,0,255);font-size:22px}
```

This is pretty good because I can strip out the first and last character to get what I want, but it would be nice if clay directly supported this kind of thing a little better. Thanks for reading.

**Comment by puffnfresh** [comment]
I've been porting Clay to PureScript and noticed this problem. This is because the combinators don't distinguish between properties under selectors and ones not under selectors.

I've been working on solving it using:

```hs
type Rendered = These Inline Sheet

render :: forall a. StyleM a -> Rendered
render = rules [] <<< runS
```

https://github.com/slamdata/purescript-css/blob/5adfef09ec6fe5a8e6a6134ddbc93485bcb3a64c/src/Css/Render.purs#L31

This type allows you to have blocks of style under a selector and also not. Rendering will just give both inline and stylesheet results.

**Comment by puffnfresh** [comment]
I'm very happy to port my changed type back if people think it's an acceptable solution.

**Comment by seanparsons** [comment]
@puffnfresh I'll happily look over any PR on this front!

**Comment by turion** [comment]
@puffnfresh New maintainer here :) do you still want to port your change back?

**Comment by iclanzan** [comment]
I believe this has been solved by https://github.com/sebastiaanvisser/clay/pull/127. One can now write:

```haskell
renderWith htmlInline [] myCss
```

in order to get a string suitable for inline styles.

**Comment by turion** [comment]
@iclanzan Agree.
