### ISSUE TITLE
Incorrect values for HSL

### ISSUE THREAD

**Issue by adius** [sebastiaanvisser/clay#153]
`hsl 0 0.2 0.7` must yield `hsl(0, 20%, 70%)`
(and not `hsl(0, 0.2%, 0.7%)`)

**Comment by adius** [comment]
If this is too much of a breaking change, we could also introduce a `hslNorm` or similar function which each value `0 < x <= 1` (which makes much more sense anyways if you ask me)

**Comment by turion** [comment]
@ad-si I think we shouldn't change the existing behaviour of that function since many people rely on it already. Introducing a new function would be fine for me, but is secondary. The most important step right now is to document that `hsl` expects a percentage. That would be necessary (and sufficient) IMO to close the issue. PR welcome.
