### ISSUE TITLE
Do not pretty print redundant * before refinements

### ISSUE THREAD

**Issue by jameshfisher** [sebastiaanvisser/clay#25]

**Comment by turion** [comment]
In case you're still active here: Do you think your issue is solved by #186?

**Comment by typedrat** [comment]
Not OP, but I think this issue's approach is right and #185/#186 are wrong. Part of good DSL design should be about representing the _meaning_ of the output and not just transcribing it into a different syntax.

It's a contrived example, but imagine you have something like this:

```haskell
sels :: [Selector]
refs :: [Refinement]

refinedSels :: [Selector]
refinedSels = zipWith (#) sels refs
```

Printing the simpler syntax of just the refinement rather than the selector first allows `star` to just get added to `sels` and treated uniformly, whereas adding a new function from `Refinement`s to `Selector`s would require special casing.

**Comment by turion** [comment]
Ah, this would have helped in #206 as well, right?

**Comment by turion** [comment]
In fact I believe that `star # refinement` already does not print the redundant `*`. If this is true I'll happily accept a PR adding a function like `refinementSel` with a unit test case.
